### ISSUE TITLE
python2 support?

### ISSUE THREAD

**Issue by papagandalf** [pltrdy/rouge#1]
Are you planning to support python 2? 
I feel minimal changes will make it runnable on python2.

**Comment by pltrdy** [comment]
Just quickly tried. I only had import issues on my side.
512a743f0dd5f4cab229b334df8f499c7ef60ae1 solved it using.

Tell me if it is ok for you now.

**Comment by papagandalf** [comment]
Yes, it's fine! Thanks! Should I leave the issue open until you sync the repo with pypi, so that pip2 downloads the right version?

**Comment by pltrdy** [comment]
It's updated
