### ISSUE TITLE
missing dependency, six?

### ISSUE THREAD

**Issue by AlJohri** [pltrdy/rouge#15]
looks like the dependency `six` is missing from setup.py? might need to add via `install_requires`

```
Collecting rouge>=0.2.1 (from newssum==0.1.0)
  Downloading https://files.pythonhosted.org/packages/7e/20/d351e85280517183b5b8460a0f47622f3b44c3eabdecd012313680576f35/rouge-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/c5/sxpknfp571v3ydglf4305g9m0000gn/T/pip-install-gu3hvo89/rouge/setup.py", line 2, in <module>
        import rouge
      File "/private/var/folders/c5/sxpknfp571v3ydglf4305g9m0000gn/T/pip-install-gu3hvo89/rouge/rouge/__init__.py", line 2, in <module>
        from rouge.rouge import FilesRouge, Rouge
      File "/private/var/folders/c5/sxpknfp571v3ydglf4305g9m0000gn/T/pip-install-gu3hvo89/rouge/rouge/rouge.py", line 3, in <module>
        import six
    ModuleNotFoundError: No module named 'six'
```

**Comment by guillaumekln** [comment]
The issue is that the module is imported in its `setup.py`. So the dependencies are required before even parsing the file that lists the dependencies.

**Comment by pltrdy** [comment]
Good point @guillaumekln 

I'm wondering providing a requirement list (aka. `requirements.txt`) in order to install it first (e.g. using `pip install -r`). This would solve this issue. 

I could also remove `import` in `setup.py` but I do like using the module's `__version__` directly.

**Comment by guillaumekln** [comment]
IMO removing the import in `setup.py` is the way to go. It duplicates the version string but that should be manageable.

Currently, the package on PyPi can't be used in other projects' `setup.py` because of this issue.

**Comment by pltrdy** [comment]
Make sense. I'll look into it.

**Comment by pltrdy** [comment]
(I made a new release `0.3.1`, available on PyPi with this fix)

**Comment by ioana-blue** [comment]
I still see this issue when I installed `0.3.2` with pip under anaconda.
