### ISSUE TITLE
Score differences from README

### ISSUE THREAD

**Issue by ZhaofengWu** [pltrdy/rouge#20]
I'm running the example code from your README, but I got some quite different numbers from there:

![image](https://user-images.githubusercontent.com/11954789/46895622-1cb15000-ce2e-11e8-919d-1710641c0824.png)

Do you have any idea why that is? (Python 3.6.4)

**Comment by pltrdy** [comment]
Hi,

Thanks for pointing this out. In fact, umbers in the readme are outdated, it has been produced with an old version of the code. With current code I'm getting same results, no bug here. I'll update.
