### ISSUE TITLE
rouge-L total number of words in sentences

### ISSUE THREAD

**Issue by rjh7008** [pltrdy/rouge#27]
thanks for making useful library.
I got a question about implementing of ROUGE-L

In code, To get "m" and "n",  you used len(**set**(_split_into_words(reference_sentences))).
but in paper, it does not seem number of unique words.
I am not familiar in perl code, but original perl code also does not seem unique words.

is there some reason you use unique words count?

**Comment by pltrdy** [comment]
It make sense. We would need to compare scores with quite repetitive inputs then.

All experiments and/or PR on that would be welcome!!

**Comment by pltrdy** [comment]
I've been experimenting with it, your remark is correct and apply to all ROUGE metrics.
It's fixed in:
https://github.com/pltrdy/rouge/pull/38
