### ISSUE TITLE
Typo in documentation 

### ISSUE THREAD

**Issue by jindrahelcl** [pltrdy/rouge#3]
Hi, I noticed an error in the documentation you have on PyPI (maybe it's used elsewhere as well):

```python
from rouge import Rouge 

hypothesis = "the #### transcript is a written version of each day 's cnn student news program use this transcript to he lp students with reading comprehension and vocabulary use the weekly newsquiz to test your knowledge of storie s you saw on cnn student news"

reference = "this page includes the show transcript use the transcript to help students with reading comprehension and vocabulary at the bottom of the page , comment for a chance to be mentioned on cnn student news . you must be a teac her or a student age # # or older to request a mention on the cnn student news roll call . the weekly newsquiz tests students ' knowledge of even ts in the news"

rouge = Rouge()
scores = rouge.get_scores(reference, hypothesis)
```

according to the code (and the examples below this excerpt), hypothesis should go first.

**Comment by pltrdy** [comment]
@jindrahelcl thanks for pointing this out, that's true. 

I'll fix it, just note that it is not really important as the ROUGE scoring is [commutative](https://en.wikipedia.org/wiki/Commutative_property)

**Comment by sai-prasanna** [comment]
Empirically score varied for me, I think it maybe because the reference should be a triply nested list and hypothesis doubly nested. So the get_scores is not commutative eventhough rouge recall is.
