### ISSUE TITLE
No module named 'bin' after pip install 

### ISSUE THREAD

**Issue by shahbazsyed** [pltrdy/rouge#30]
After successfully installing using `pip install rouge` , I get the following when trying `rouge -h`
```
Traceback (most recent call last):
  File "/usr/local/bin/rouge", line 6, in <module>
    from bin.rouge_cmd import main
ModuleNotFoundError: No module named 'bin'
```
I do not get this error when installing using `git clone`.

**Comment by pltrdy** [comment]
Thanks for pointing this out. 

I made a new release and published it on `pip`, it should be ok now.
