### ISSUE TITLE
Not working. Help!

### ISSUE THREAD

**Issue by kevinborg** [pltrdy/rouge#32]
I am following the example found in the readme file using rouge as a library but when I pass the original summary and the predicted summary as a string rouge scores are all 0. Can you help me with this issue please ? I have uploaded an image for your referrence.

![image](https://user-images.githubusercontent.com/16855972/58240593-9c4fb780-7d4b-11e9-8f84-61aac42b7ec8.png)

**Comment by pltrdy** [comment]
It is working, scores are `0.0` in your case. Check your `hyps` and `refs`, there's no match.

**Comment by kevinborg** [comment]
Thanks for the fast reply! Although I don't quite think this is working for me because I have tried using a different library and got results for rouge-1 
![image](https://user-images.githubusercontent.com/16855972/58252036-70413000-7d65-11e9-8d8c-c366c1d3c3d8.png)

I would like to use this library because it provides results for rouge-2 and rouge-l which is also what I need. Do you have any idea what could be the problem ? 

ps. i have used different sentences and also still no results. When I use the sample it provided in the readme it works though. Cannot understand what the problem is. please help.

**Comment by pltrdy** [comment]
Do you know what ROUGE is? 

For instance, ROUGE-1 calculates the proportion of word match = words that are the same in hyp/ref. You provided an example without any word in common between hypothesis and reference, how could you expect something different from 0?

**Comment by kevinborg** [comment]
Although I am new to this, yes I know what ROUGE is and agree with your definition of rouge-1. What frustrates me is that the print screen of the library used above gives me some results and this library does not give me results. Thanks for your help anyway.

**Comment by pltrdy** [comment]
Could you print the sentence(s) used in the second case? Really doubt it's the same, or the problem is here.

**Comment by kevinborg** [comment]
![image](https://user-images.githubusercontent.com/16855972/58256182-df6f5200-7d6e-11e9-8f47-58dcbc00296c.png)

Below is the class i am using from PyRouge. Although rouge-2 method is there i do not know how to use it and get_bigram_count seems to be also missing. 

`from __future__ import division
from itertools import chain


def get_unigram_count(tokens):
    count_dict = dict()
    for t in tokens:
        if t in count_dict:
            count_dict[t] += 1
        else:
            count_dict[t] = 1

    return count_dict


class Rouge:
    beta = 1

    @staticmethod
    def my_lcs_grid(x, y):
        n = len(x)
        m = len(y)

        table = [[0 for i in range(m + 1)] for j in range(n + 1)]

        for j in range(m + 1):
            for i in range(n + 1):
                if i == 0 or j == 0:
                    cell = (0, 'e')
                elif x[i - 1] == y[j - 1]:
                    cell = (table[i - 1][j - 1][0] + 1, '\\')
                else:
                    over = table[i - 1][j][0]
                    left = table[i][j - 1][0]

                    if left < over:
                        cell = (over, '^')
                    else:
                        cell = (left, '<')

                table[i][j] = cell

        return table

    @staticmethod
    def my_lcs(x, y, mask_x):
        table = Rouge.my_lcs_grid(x, y)
        i = len(x)
        j = len(y)

        while i > 0 and j > 0:
            move = table[i][j][1]
            if move == '\\':
                mask_x[i - 1] = 1
                i -= 1
                j -= 1
            elif move == '^':
                i -= 1
            elif move == '<':
                j -= 1

        return mask_x

    @staticmethod
    def rouge_l(cand_sents, ref_sents):
        lcs_scores = 0.0
        cand_unigrams = get_unigram_count(chain(*cand_sents))
        ref_unigrams = get_unigram_count(chain(*ref_sents))
        for cand_sent in cand_sents:
            cand_token_mask = [0 for t in cand_sent]
            cand_len = len(cand_sent)
            for ref_sent in ref_sents:
                # aligns = []
                # Rouge.lcs(ref_sent, cand_sent, aligns)
                Rouge.my_lcs(cand_sent, ref_sent, cand_token_mask)

                # for i in aligns:
                #     ref_token_mask[i] = 1
            # lcs = []
            cur_lcs_score = 0.0
            for i in range(cand_len):
                if cand_token_mask[i]:
                    token = cand_sent[i]
                    if cand_unigrams[token] > 0 and ref_unigrams[token] > 0:
                        cand_unigrams[token] -= 1
                        ref_unigrams[token] -= 1
                        cur_lcs_score += 1

                        # lcs.append(token)

            # print ' '.join(lcs)

            lcs_scores += cur_lcs_score

        # print "lcs_scores: %d" % lcs_scores
        ref_words_count = sum(len(s) for s in ref_sents)
        # print "ref_words_count: %d" % ref_words_count
        cand_words_count = sum(len(s) for s in cand_sents)
        # print "cand_words_count: %d" % cand_words_count

        precision = lcs_scores / cand_words_count
        recall = lcs_scores / ref_words_count
        f_score = (1 + Rouge.beta ** 2) * precision * recall / (recall +
                                                                Rouge.beta ** 2 * precision + 1e-7) + 1e-6  # prevent underflow
        return precision, recall, f_score

    @staticmethod
    def rouge_2(cand_sents, ref_sents):
        cand_bigram_counts = get_bigram_counts(cand_sents)
        ref_bigram_counts = get_bigram_counts(ref_sents)`
