### ISSUE TITLE
Lengths of Reference and System Summaries

### ISSUE THREAD

**Issue by MehwishFatimah** [pltrdy/rouge#37]
Hi,
I am using this packing for evaluation. 
Thank you for a python developed version of Rouge.
However, I am concerned about why equal lengths of reference and system summaries are required. 
To my understanding, there should be no restriction for equal lengths.
Please check the following link:
https://rxnlp.com/how-rouge-works-for-evaluation-of-summarization-tasks/#.Xd-VSFlKg2c

May you please provide any explanation of your code condition for equal lengths.
Looking forward for your kind response.

**Comment by pltrdy** [comment]
Indeed, there's no lengths requirements for ROUGE scoring at sequence level.

It think you're mentioning files scoring restriction that is on number of lines. In fact, for file scoring, we expect one sequence per line, thus there must be as many hypothesis as references.

**Comment by MehwishFatimah** [comment]
Thanks for prompt response.
If I pass reference and system summaries of different lengths (let say I have only 1 example), so this code throws an error that reference and system (hypothese) are not of equal lengths.
Below is the snippet of your code.
----------------------------
def get_scores(self, hyps, refs, avg=False):
        if isinstance(hyps, six.string_types):
            hyps, refs = [hyps], [refs]

        assert(type(hyps) == type(refs))
        assert(len(hyps) == len(refs))

        if not avg:
            return self._get_scores(hyps, refs)
        return self._get_avg_scores(hyps, refs)
-----------------------------------

Moreover, I am interested that how accurate this Rouge scoring is, or in other words, how similar it is to the actual implementation in terms of results.

**Comment by pltrdy** [comment]
Again, I'm not limiting "length" as understood as "number of words in a sequences" but the length on the set of sequences, i.e. the number of examples.

I discuss accuracy here: https://github.com/pltrdy/rouge/issues/2#issuecomment-366320141 

ROUGE is meant to be purely pythonic and fast (it does not rely on original perl code, does not write files etc), however, for accurate scoring I also use https://github.com/pltrdy/files2rouge which has this constraint too.

**Comment by colaaaaaa** [comment]
hello, i am confused the same question with her, she means that when the num of sentences in hyp are not the same with the num of sentences in reference, it  throws the assert error:assert(len(hyps) == len(refs))
i do think there should not be constrain in the length of the hyp, the length means the sentence of the hyp, in the document summarization task, the summarization of the document can be several sentence~

**Comment by pltrdy** [comment]
@colaaaaaa that's not what it means. In this context, lengths are the number of examples, e.g. pairs of summaries (of any length), and reference (on any lengths) w/ both summary/references are on a single line (even if multi-sentences)

**Comment by colaaaaaa** [comment]
yes!! i found that  when i go to the codes in detail,
but i got another question:  how  & why the python implemention of rouge runs faster than the perl ROUGE 1.5.5 ? 
 thx ,sorry to bother u!!!!!! and appreciate your patience!!!!!
