### ISSUE TITLE
FilesRouge args error

### ISSUE THREAD

**Issue by Sanghyuk-Choi** [pltrdy/rouge#39]
```
from rouge import FilesRouge
files_rouge = FilesRouge()
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() missing 2 required positional arguments: 'hyp_path' and 'ref_path'

**Comment by Sanghyuk-Choi** [comment]
I think it's fine with installing package by cloning git.
but if I install by pip, error happens.

**Comment by pltrdy** [comment]
@Sanghyuk-Choi Hey, it's the wrong repo (`files2rouge != rouge`) but anyway, I maintain both.

files2rouge cannot be installed w/ pip, and, yes, dependencies must be cloned, not installed with pip.
