### ISSUE TITLE
Unicode Decode Error Bug ?

### ISSUE THREAD

**Issue by dylanee2** [pltrdy/rouge#4]
while using the library, I got the following error 
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 33: ordinal not in range(128)

at 
split_into_words
    return list(itertools.chain(*[_.split(" ") for _ in sentences]))

How should I fix it?

**Comment by pltrdy** [comment]
Could you provide full stack trace?

I need to see where in the code this is happening. 

Then I'll provide a fix, must be my bad.
