### ISSUE TITLE
Running the provided example but getting an empty dict as output.

### ISSUE THREAD

**Issue by seanswyi** [pltrdy/rouge#43]
Hi. I'm running the example line by line as is shown in the README file, but I'm getting an empty dictionary as the output. Any insight on how I can fix this and what might be the cause? Thanks.

**Comment by pltrdy** [comment]
Could you provide a code example of what you ran?

Are the files actually *not* empty?

**Comment by seanswyi** [comment]
I'm actually not running with files. I just tested out the "as a library" example.

I literally just opened a new IPython session and did:

```Python
In [1]: from rouge import Rouge 
In [2]: hypothesis = "the #### transcript is a written version of each day 's cnn student news program use this transcript to he    lp students with reading comprehension and vocabulary use the weekly newsquiz to test your knowledge of storie s you     saw on cnn student news"
In [3]: reference = "this page includes the show transcript use the transcript to help students with reading comprehension and     vocabulary at the bottom of the page , comment for a chance to be mentioned on cnn student news . you must be a teac    her or a student age # # or older to request a mention on the cnn student news roll call . the weekly newsquiz tests     students ' knowledge of even ts in the news"
In [4]: rouge = Rouge()
In [5]: scores = rouge.get_scores(hypothesis, reference)
In [6]: scores
Out[6]: {}
```
Am I missing something here?

**Comment by pltrdy** [comment]
I do get some results for the same commands...
```
In [5]: rouge.get_scores(hypothesis, reference)
Out[5]: 
[{'rouge-1': {'f': 0.49411764217577864,
   'p': 0.5833333333333334,
   'r': 0.42857142857142855},
  'rouge-2': {'f': 0.23423422957552154,
   'p': 0.3170731707317073,
   'r': 0.18571428571428572},
  'rouge-l': {'f': 0.42751590030718895,
   'p': 0.5277777777777778,
   'r': 0.3877551020408163}}]
```

Maybe try to upgrade your `rouge` version (might be unstable?)

**Comment by seanswyi** [comment]
That is really really strange... I'll try updating and looking into other possible factors and get back to you.

**Comment by seanswyi** [comment]
Well, updating didn't solve the issue but cloning and building from source did. I'm getting similar results as you are:

```Python
[{'rouge-1': {'f': 0.4786324739396596,
   'p': 0.6363636363636364,
   'r': 0.3835616438356164},
  'rouge-2': {'f': 0.2608695605353498,
   'p': 0.3488372093023256,
   'r': 0.20833333333333334},
  'rouge-l': {'f': 0.44705881864636676,
   'p': 0.5277777777777778,
   'r': 0.3877551020408163}}]
```

Is there some reason why there are discrepancies between building from source and using `pip install`? If there's not any obvious reason I think you can close the issue.

**Comment by pltrdy** [comment]
I do not understand to be honest. I also uninstalled then pip installed (i.e. rouge 1.0.0) and it worked fine.

Weird, I'm closing tho, happy that your problem is sloved :)
