### ISSUE TITLE
Just making sure, ROUGE scores are within [0, 1] right?

### ISSUE THREAD

**Issue by seanswyi** [pltrdy/rouge#45]
Common sense tells me that for all three available scores (i.e. `rouge-1`, `rouge-2`, and `rouge-l`) the values for each entry should be between [0, 1], but I'm getting values like 7.8 and 6.4 for `rouge-2` for some of my stuff.

I'm assuming that there's also a problem on my side, but just wanted to make sure.

**Comment by pltrdy** [comment]
Hmm could you post some examples?

**Comment by Sanghyuk-Choi** [comment]
I've got similar issue.
using files rouge, avg option.
{'rouge-1': {'f': 0.6980119307776039, 'p': 0.8065670283914737, 'r': 0.6324478097808415}, 'rouge-2': {'f': 0.562795798097856, 'p': 0.6499996714358559, 'r': 0.5102179338575358}, 'rouge-l': **{'f': 2.861890612988861, 'p': 3.3276519933008513, 'r': 2.5831437788336338}}**

**Comment by pltrdy** [comment]
@Sanghyuk-Choi yes, probably fixed by https://github.com/pltrdy/rouge/pull/38/commits/4cfd4c7e2fc3582d93df811f33cc0b080bebaafb

**Comment by seanswyi** [comment]
Sorry for being MIA. Unfortunately I don't know if I'll be able to reproduce the exact results, but fortunately it seems like it's been solved. I'll close this Issue for now and either reopen it or open a new one if I encounter the same problem again. Thanks!
