### ISSUE TITLE
Scores are not matching readme

### ISSUE THREAD

**Issue by alexgaskell10** [pltrdy/rouge#46]
Have run the code in the readme and it is not matching the output, nor does it match #20.

My scores are:
[{'rouge-1': {'f': 0.4786324739396596, 'p': 0.6363636363636364, 'r': 0.3835616438356164}, 'rouge-2': {'f': 0.2608695605353498, 'p': 0.3488372093023256, 'r': 0.20833333333333334}, 'rouge-l': {'f': 0.44705881864636676, 'p': 0.5277777777777778, 'r': 0.3877551020408163}}]

Can you confirm if these are correct?

**Comment by pltrdy** [comment]
@alexgaskell10 That's correct, I do replicate your results. I'm updating the README, thanks.
