### ISSUE TITLE
empty result

### ISSUE THREAD

**Issue by demdecuong** [pltrdy/rouge#50]
I am using this snippet 

from rouge import Rouge

hypothesis = "the #### transcript is a written version of each day 's cnn student news program use this transcript to he    lp students with reading comprehension and vocabulary use the weekly newsquiz to test your knowledge of storie s you     saw on cnn student news"

reference = "this page includes the show transcript use the transcript to help students with reading comprehension and     vocabulary at the bottom of the page , comment for a chance to be mentioned on cnn student news . you must be a teac    her or a student age # # or older to request a mention on the cnn student news roll call . the weekly newsquiz tests     students ' knowledge of even ts in the news"

rouge = Rouge()
scores = rouge.get_scores(hypothesis, reference)

And get the empty result {}

**Comment by pltrdy** [comment]
I'm not reproducing the error. For me `scores` contain the actual scores. Be sure you are up to date or run `pip install -U rouge`.

**Comment by jind11** [comment]
I encountered the same error with  python==3.6 env. After upgrading rouge package, I got this message:
Requirement already up-to-date: rouge in /home/ec2-user/anaconda3/envs/KMDM/lib/python3.6/site-packages (1.0.0)
Requirement already satisfied, skipping upgrade: six in /home/ec2-user/anaconda3/envs/KMDM/lib/python3.6/site-packages (from rouge) (1.15.0)
