### ISSUE TITLE
Does it support Chinese?

### ISSUE THREAD

**Issue by fresh382227905** [pltrdy/rouge#51]
I used it to evaluate the performence of generated sentences which is Chinese, But it got  [{'rouge-1': {'f': 0.0, 'p': 0.0, 'r': 0.0}, 'rouge-2': {'f': 0.0, 'p': 0.0, 'r': 0.0}, 'rouge-l': {'f': 0.0, 'p': 0.0, 'r': 0.0}}].
Could you tell me what should I do ?
Looking forward to your reply, Thanks sincerely!

**Comment by pltrdy** [comment]
Can you provide some examples from the texts you are trying to process. It should theoretically be possible. Note that ROUGE count word match, with "word" being anything separated by a whitespace. 

For example we could run ROUGE on the text "A BB CCC" that would be considered as 3 words. I'm not sure whether it's relevant or not to process chinese.

**Comment by fresh382227905** [comment]
Thanks! It can process Chinese text.
Follwing your suggestions, I solved this problem.
