### ISSUE TITLE
ValueError despite ignore_empty flag being True 

### ISSUE THREAD

**Issue by am-berry** [pltrdy/rouge#53]
Hi, firstly thanks for this great package!
I've been using it the last few days to some success but one problem keeps arising. Even though I have the ignore_empty flag set to True, I still get a `ValueError: Hypothesis is empty.` 

I'm not sure why this is happening. The generated/reference summaries are so large that it's hard to look through, and there's no callback from the package to see which example is causing the error.

Here's the code I'm running to get the error:

```python
from rouge import Rouge 
rouge = Rouge()
scores = rouge.get_scores(generated.tolist(), references.tolist(), avg=True, ignore_empty=True)
```

(It's a little hard/useless to show the code used to generate the two lists)
Looking through the source code, I can't see why it's erroring out, as both the hypothesis and reference summaries' lengths are checked for being nonzero with this flag set.

Any suggestions as to what I'm doing wrong here? 

Also related: would it be possible to add a callback where it says the list index which causes the error?

**Comment by gooppe** [comment]
I just encountered a similar problem. Apparently, the problem is processing strings consisting of dots.

How to reproduce:

```python
from rouge import Rouge 
rouge = Rouge()

hyps = [".", "1"]
refs = ["2", "3"]

rouge.get_scores(hyps, refs, avg=False, ignore_empty=True)
```

The reason is the splitting sentences by dots and filtering them by zero length: https://github.com/pltrdy/rouge/blob/6d443d9c95d86cce4629ef0410110a76077498fb/rouge/rouge.py#L140

@am-berry, as a quick fix, you can filter all your hypotheses from lines consisting of dots.

**Comment by am-berry** [comment]
@gooppe Thanks for the quick reply! 
Looks like that was indeed the problem and filtering for it fixed the problem. Thanks again!

I'm going to leave the issue open for the time being as it's probably worth a fix within the package itself...
