### ISSUE TITLE
Rouge-l results changed significantly from previous version

### ISSUE THREAD

**Issue by fabrahman** [pltrdy/rouge#57]
Hi,
I have been working with an older version of your implementation in 2020, and now I reinstall the package. I realized while rouge scores decreased in general in the current implementation, the rouge-l (f1) decreased significantly almost around -150%. I was wondering if there is any issue?

Thanks

**Comment by pltrdy** [comment]
Can you be be more specific about previous version used, the evaluated text (if sharable) and the scores

**Comment by fabrahman** [comment]
Hi @pltrdy Thanks for getting back to me.
Actually when I check the repo, it seems like there is not any new commit expect adding rouge 3- 5.
Earlier in Sept, I installed rouge from source and I got following scores:

```
Model	ROUGE-1	ROUGE-2	ROUGE-L
M1	26.620	5.362	54.078
M2	21.447	4.642	42.077
M3	20.875	3.534	44.800
M4	21.578	4.575	42.699
M5	21.879	4.880	42.860
M6	21.213	4.427	41.911
M7	19.576	3.164	40.460
```
However, on the same input, now after reinstalling (from source) , I got:

```
Model	ROUGE-1	ROUGE-2	ROUGE-L
M1	24.927	5.427	21.986
M2	21.467	4.659	19.368
M3	19.246	3.502	17.517
M4	21.331	4.663	19.064
M5	21.794	4.872	19.604
M6	21.180	4.403	19.128
M7	18.694	3.153	16.909
```
Unfortunately, I don't have the previous rouge code to compare. I am kind of clueless. Rouge 1, 2 are more or less the same, but rouge-l ...

**Comment by pltrdy** [comment]
Short answer: this score is *probably* the right one, the previous one was erroneous (sorry for that).
Note that ROUGE-L usually gets values similar -- but lower -- than ROUGE-1. This gives you a first hint that the first results are wierd.

Long answer:
There have been some fixes about the ROUGE-L metric over the past months.
For references :
* Issue in ROUGE-L with `exclusive` (see issue: https://github.com/pltrdy/rouge/issues/41 and fix: https://github.com/pltrdy/rouge/commit/d8b8a5b47dfb8a15a4c834a62e3801283e630e62
* Also, a fix about F1 score calculation for ROUGE-L : https://github.com/pltrdy/rouge/commit/12ed0ade0350fbd211e73b8c524b09e1266c598f

A good check is to use both this (fully Python) package along with https://github.com/pltrdy/files2rouge which uses the official implementation.

I close the issue, sorry again for the misscalculations.
