### ISSUE TITLE
In the released version on pypi.org, the score of rouge-L was still set exclusive = True

### ISSUE THREAD

**Issue by anwjedb** [pltrdy/rouge#62]
I am puzzled, the newest code of this repository has fixed this problem, as shown here：[https://github.com/pltrdy/rouge/pull/48#issue-454627638](url), also in the released version 1.0.0. But not fixed in the released version on pypi.org, so when using 'pip install rouge' to install, the problem still exists

**Comment by pltrdy** [comment]
Thats correct, I updated `rouge`. Thanks.
