### ISSUE TITLE
README same scores format regardless of avg value?

### ISSUE THREAD

**Issue by UrosOgrizovic** [pltrdy/rouge#63]
In the `README.md` file, both outputs are the same, regardless of whether `avg=False` or `avg=True`:

```{"rouge-1": {"f": _, "p": _, "r": _}, "rouge-2" : { .. }, "rouge-l": { ... }}```

Am I missing something or should this be fixed so that the two outputs aren't the same (list of dicts vs single dict)?

**Comment by pltrdy** [comment]
Your understanding is right and so is the package, the `README.md` is wrong.

I'm fixing, thanks.
